### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by pkgoyal86** [podio/jquery-mentions-input#153]
Neither demo nor code is working. There is some js error.

Please check below image link

http://s29.postimg.org/qyuc7bwrb/error.jpg

Thanks

**Comment by kenarai** [comment]
Seconded. Same problem here as well.

**Comment by berkayk** [comment]
Same as well. Underscore is not loading.

    Failed to load resource: the server responded with a status of 404 (Not Found) http://documentcloud.github.io/underscore/underscore-min.js
    jquery.mentionsInput.js:387 Uncaught ReferenceError: _ is not defined
    examples.js:3 Uncaught TypeError: $(...).mentionsInput is not a function

**Comment by chasd00** [comment]
I submitted a pull request for this, clone the repo, open index.html and change the reference to underscore.js to 
https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js

after that it'll work

**Comment by praveenscience** [comment]
This has been fixed. :smiley:

**Comment by ghost** [comment]
@chasd00 @praveenscience Is there a chance the issue is back? See https://github.com/podio/jquery-mentions-input/issues/184

**Comment by praveenscience** [comment]
@silentsnooc I did check it now and it worked fine for me. Checking #184 again.
